COMPARATOR: list[str] = [
    "==",
    "like",
    "equal",
    "eq",
    "sama dengan",
    "!=",
    "ne",
    "not equal",
    "tidak sama dengan",
    ">",
    "gt",
    "greater than",
    "lebih besar",
    "lebih besar dari",
    "<",
    "lt",
    "less than",
    "kurang",
    "kurang dari",
    ">=",
    "gte",
    "greater than equal",
    "lebih besar sama dengan",
    "<=",
    "lte",
    "less than equal",
    "kurang dari sama dengan",
]
